/*
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. OpenMRS is also distributed under
 * the terms of the Healthcare Disclaimer located at http://openmrs.org/license.
 *
 * Copyright (C) OpenMRS Inc. OpenMRS is a registered trademark and the OpenMRS
 * graphic logo is a trademark of OpenMRS Inc.
 */
package org.openmrs.module.auditlogweb.api.dao;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.boot.Metadata;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistry;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.envers.AuditReader;
import org.hibernate.envers.AuditReaderFactory;
import org.hibernate.envers.Audited;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.mockito.MockedStatic;
import org.openmrs.api.context.Context;
import org.openmrs.api.context.Daemon;
import org.openmrs.api.context.UserContext;
import org.openmrs.api.db.hibernate.HibernateSessionFactoryBean;
import org.openmrs.api.db.hibernate.envers.OpenmrsRevisionEntity;
import org.openmrs.module.auditlogweb.api.dao.AuditBackfillDao.SchemaCreationResult;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.mockStatic;
import static org.mockito.Mockito.when;

/**
 * Boots a real Hibernate + Envers SessionFactory against in-memory H2 with only the base tables
 * present, then verifies that {@link AuditBackfillDao#createMissingAuditTables()} creates a schema
 * Envers can actually write to and read back from — including the relation audit table for a
 * unidirectional collection (the Location_LocationAttribute case), which has no base table.
 */
class AuditBackfillDaoIntegrationTest {
	
	private static StandardServiceRegistry serviceRegistry;
	
	private static Metadata metadata;
	
	private static SessionFactory sessionFactory;
	
	private static AuditBackfillDao dao;
	
	@BeforeAll
	static void bootHibernateWithOnlyBaseTables() {
		serviceRegistry = new StandardServiceRegistryBuilder()
		        .applySetting("hibernate.dialect", "org.hibernate.dialect.H2Dialect")
		        .applySetting("hibernate.connection.driver_class", "org.h2.Driver")
		        .applySetting("hibernate.connection.url",
		            "jdbc:h2:mem:auditbackfill;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=TRUE")
		        .applySetting("hibernate.connection.username", "sa").applySetting("hibernate.connection.password", "")
		        .applySetting("hibernate.hbm2ddl.auto", "none").applySetting("hibernate.id.new_generator_mappings", "false")
		        .applySetting("hibernate.integration.envers.enabled", "true").build();
		
		metadata = new MetadataSources(serviceRegistry).addAnnotatedClass(OpenmrsRevisionEntity.class)
		        .addAnnotatedClass(Book.class).addAnnotatedClass(Page.class).buildMetadata();
		sessionFactory = metadata.buildSessionFactory();
		
		try (Session session = sessionFactory.openSession()) {
			session.doWork(connection -> {
				try (java.sql.Statement statement = connection.createStatement()) {
					statement.execute("create table test_book (id integer generated by default as identity primary key, "
					        + "title varchar(100))");
					statement.execute("create table test_page (id integer generated by default as identity primary key, "
					        + "content varchar(100), book_id integer)");
				}
			});
		}
		
		dao = new AuditBackfillDao(sessionFactory);
	}
	
	@AfterAll
	static void shutDown() {
		if (sessionFactory != null) {
			sessionFactory.close();
		}
		if (serviceRegistry != null) {
			StandardServiceRegistryBuilder.destroy(serviceRegistry);
		}
	}
	
	@Test
	void shouldCreateSchemaEnversCanWriteToAndReadBack() {
		try (MockedStatic<Context> context = mockStatic(Context.class);
		        MockedStatic<Daemon> daemon = mockStatic(Daemon.class)) {
			HibernateSessionFactoryBean sessionFactoryBean = mock(HibernateSessionFactoryBean.class);
			when(sessionFactoryBean.getMetadata()).thenReturn(metadata);
			context.when(() -> Context.getRegisteredComponents(HibernateSessionFactoryBean.class))
			        .thenReturn(Collections.singletonList(sessionFactoryBean));
			
			UserContext userContext = mock(UserContext.class);
			when(userContext.isAuthenticated()).thenReturn(false);
			context.when(Context::getUserContext).thenReturn(userContext);
			daemon.when(Daemon::getDaemonThreadUser).thenReturn(null);
			
			// revision_entity + test_book_AUD + test_page_AUD (cloned) + the relation table (via migration)
			SchemaCreationResult result = dao.createMissingAuditTables();
			assertEquals(4, result.getCreated());
			assertTrue(result.getMissingTables().isEmpty(),
			    "expected no missing Envers tables but got: " + result.getMissingTables());
			
			// a second run must be a clean no-op
			SchemaCreationResult secondRun = dao.createMissingAuditTables();
			assertEquals(0, secondRun.getCreated());
			assertTrue(secondRun.getMissingTables().isEmpty());
			
			// revision-only lookups filter on REV without the base id, so REV must lead an index
			assertTrue(hasIndexLedByRev("test_book_AUD"), "expected an index with REV as its leading column");
			
			// audited write: entity plus a collection element, exercising the relation audit table
			Integer bookId;
			try (Session session = sessionFactory.openSession()) {
				Transaction tx = session.beginTransaction();
				Book book = new Book();
				book.title = "dracula";
				Page page = new Page();
				page.content = "chapter one";
				book.pages.add(page);
				session.save(book);
				tx.commit();
				bookId = book.id;
			}
			assertNotNull(bookId);
			
			// read the revision back through Envers
			try (Session session = sessionFactory.openSession()) {
				AuditReader auditReader = AuditReaderFactory.get(session);
				List<Number> revisions = auditReader.getRevisions(Book.class, bookId);
				assertEquals(1, revisions.size());
				
				Book atRevision = auditReader.find(Book.class, bookId, revisions.get(0));
				assertEquals("dracula", atRevision.title);
				assertEquals(1, atRevision.pages.size());
				
				// the relation audit table (no base table) must exist and hold the collection row
				String middleAuditTable = findMiddleAuditTableName();
				Number middleRows = (Number) session.createNativeQuery("select count(*) from " + middleAuditTable)
				        .getSingleResult();
				assertEquals(1, middleRows.intValue());
			}
			
			// simulate a platform upgrade adding a column to the base table, then sync
			try (Session session = sessionFactory.openSession()) {
				session.doWork(connection -> {
					try (java.sql.Statement statement = connection.createStatement()) {
						statement.execute("alter table test_book add subtitle varchar(50)");
					}
				});
			}
			AuditBackfillDao.ColumnSyncResult syncResult = dao.addMissingAuditColumns();
			assertEquals(1, syncResult.getColumnsAdded());
			assertTrue(syncResult.getFailedTables().isEmpty());
			assertTrue(auditTableHasColumn("test_book_AUD", "subtitle"), "expected the synced column on the audit table");
			// and the sync itself must be idempotent and clean on re-run
			AuditBackfillDao.ColumnSyncResult secondSync = dao.addMissingAuditColumns();
			assertEquals(0, secondSync.getColumnsAdded());
			assertTrue(secondSync.getFailedTables().isEmpty());
			
			// a base column widened after the clone must be reported as a failed table, not skipped
			try (Session session = sessionFactory.openSession()) {
				session.doWork(connection -> {
					try (java.sql.Statement statement = connection.createStatement()) {
						statement.execute("alter table test_book alter column title varchar(200)");
					}
				});
			}
			AuditBackfillDao.ColumnSyncResult mismatchSync = dao.addMissingAuditColumns();
			assertEquals(0, mismatchSync.getColumnsAdded());
			assertTrue(mismatchSync.getFailedTables().contains("test_book_AUD"),
			    "expected the widened column to mark test_book_AUD as failed, got: " + mismatchSync.getFailedTables());
		}
	}
	
	private static boolean auditTableHasColumn(String tableName, String columnName) {
		try (Session session = sessionFactory.openSession()) {
			return session.doReturningWork(connection -> {
				try (java.sql.ResultSet rs = connection.getMetaData().getColumns(connection.getCatalog(), null, tableName,
				    columnName)) {
					return rs.next();
				}
			});
		}
	}
	
	private static boolean hasIndexLedByRev(String tableName) {
		try (Session session = sessionFactory.openSession()) {
			return session.doReturningWork(connection -> {
				try (java.sql.ResultSet rs = connection.getMetaData().getIndexInfo(connection.getCatalog(), null, tableName,
				    false, false)) {
					while (rs.next()) {
						if ("REV".equalsIgnoreCase(rs.getString("COLUMN_NAME")) && rs.getShort("ORDINAL_POSITION") == 1) {
							return true;
						}
					}
				}
				return false;
			});
		}
	}
	
	/** The Envers-mapped audit table that is neither an entity audit table nor the revision table. */
	private static String findMiddleAuditTableName() {
		for (org.hibernate.mapping.Table table : metadata.collectTableMappings()) {
			String name = table.getName();
			if (name.endsWith("_AUD") && !"test_book_AUD".equalsIgnoreCase(name)
			        && !"test_page_AUD".equalsIgnoreCase(name)) {
				return name;
			}
		}
		throw new IllegalStateException("no relation audit table mapped by Envers");
	}
	
	@Entity(name = "Book")
	@Table(name = "test_book")
	@Audited
	public static class Book {
		
		@Id
		@GeneratedValue
		private Integer id;
		
		@Column(name = "title")
		private String title;
		
		@OneToMany(cascade = CascadeType.ALL)
		@JoinColumn(name = "book_id")
		private Set<Page> pages = new HashSet<>();
	}
	
	@Entity(name = "Page")
	@Table(name = "test_page")
	@Audited
	public static class Page {
		
		@Id
		@GeneratedValue
		private Integer id;
		
		@Column(name = "content")
		private String content;
	}
}
